"""Update GameSession for game logic

Revision ID: 0f6dd95e8db2
Revises: cc10670df978
Create Date: 2025-06-04 19:54:46.547259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f6dd95e8db2'
down_revision = 'cc10670df978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_question_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_player_id', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key('fk_game_session_current_question_id_question', 'question', ['current_question_id'], ['id']) # Named the FK

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.drop_constraint('fk_game_session_current_question_id_question', type_='foreignkey') # Named the FK
        batch_op.drop_column('current_player_id')
        batch_op.drop_column('current_question_id')

    # ### end Alembic commands ###
