"""Add strikes, game_mode, player_who_can_steal to GameSession

Revision ID: 41f9d25976b0
Revises: fe50b8944c66
Create Date: 2025-06-04 21:07:21.635893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f9d25976b0'
down_revision = 'fe50b8944c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_question_strikes', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('game_mode', sa.String(length=20), nullable=False, server_default='active'))
        batch_op.add_column(sa.Column('player_who_can_steal', sa.String(length=100), nullable=True)) # Nullable, so no server_default needed for existing rows

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_session', schema=None) as batch_op:
        batch_op.drop_column('player_who_can_steal')
        batch_op.drop_column('game_mode')
        batch_op.drop_column('current_question_strikes')

    # ### end Alembic commands ###
