"""Initial models for Question and GameSession

Revision ID: cc10670df978
Revises:
Create Date: 2025-06-04 19:51:07.895742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc10670df978'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('game_state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_name')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('answer_choices', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('pack_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('game_session')
    # ### end Alembic commands ###
